version: "3.8"

services:
  cache:
    image: redis:4-alpine

  socket:
    image: socketcluster/socketcluster:v17.4.0
    ports:
      - "38000:8000"
    environment:
      SOCKETCLUSTER_WORKERS: 10
      SOCKETCLUSTER_BROKERS: 10

  queue:
    image: rg.fr-par.scw.cloud/funcscwmodernwmsc0jozcqg/queue_fleetbase:latest
    environment:
      #DATABASE_URL: "mysql://fleetbase_admin:Fleet-Password-123@51.159.8.181:27421/fleetbase"
      DB_DATABASE: fleetbase
      DB_HOST: "51.159.8.181"
      DB_PORT: 27421
      STOREFRONT_DB_PORT: 27421
      SANDBOX_DB_PORT: 27421
      DB_USERNAME: fleetbase_admin
      DB_PASSWORD: Fleet-Password-123
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      CACHE_PATH: /fleetbase/api/storage/framework/cache
      REDIS_HOST: "redis-16519.c311.eu-central-1-1.ec2.redns.redis-cloud.com"
      REDIS_PASSWORD: "9n5Zybqc1qoDedBUicSArgOaVVfA5Op4"
      REDIS_PORT: 16519

  console:
    ports:
      - "4200:4200"
    volumes:
      - ./console:/app/console
    image: rg.fr-par.scw.cloud/funcscwmodernwmsc0jozcqg/console_fleetbase:latest

  application:
    image: rg.fr-par.scw.cloud/funcscwmodernwmsc0jozcqg/app_fleetbase:latest
    ports:
      - "8000:8000"
    environment:
      DB_DATABASE: fleetbase
      DB_HOST: "51.159.8.181"
      DB_PORT: 27421
      STOREFRONT_DB_PORT: 27421
      SANDBOX_DB_PORT: 27421
      DB_USERNAME: fleetbase_admin
      DB_PASSWORD: Fleet-Password-123
      MAIL_FROM_ADDRESS: "hello@reveride.pro"
      MAIL_FROM_NAME: "GreenTMS"
      MAIL_HOST: "smtp.resend.com"
      MAIL_PASSWORD: "re_5i1gTSrG_3i8otZLFt9juurF9kBavR2aT"
      MAIL_PORT: 465
      MAIL_USERNAME: "resend"
      MAIL_MAILER: "smtp"
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      CACHE_PATH: /fleetbase/api/storage/framework/cache
      REDIS_HOST: "redis-16519.c311.eu-central-1-1.ec2.redns.redis-cloud.com"
      REDIS_PASSWORD: "9n5Zybqc1qoDedBUicSArgOaVVfA5Op4"
      REDIS_PORT: 16519
      SESSION_DOMAIN: reveride.pro
      BROADCAST_DRIVER: socketcluster
      APP_NAME: GreenTMS
      LOG_CHANNEL: daily
      MODEL_CACHE_ENABLED: true
      RESPONSE_CACHE_ENABLED: true
      RESPONSE_CACHE_DRIVER: redis
    depends_on:
      - queue
